version: '3.8'

services:
  app:
    build: .
    container_name: imnotabot-landing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imnotabot-front.rule=Host(`imnotabot.879.ai`)"
      - "traefik.http.routers.imnotabot-front.entrypoints=websecure"
      - "traefik.http.routers.imnotabot-front.tls.certresolver=le"
      - "traefik.http.services.imnotabot-front.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
    name: 879_web

